// Writes src/lib/exercise-anim/index.ts: which exercise names have an
// animation, and what each one works. The drawings themselves are too heavy
// to ship to the browser just to answer "is there one?", so client components
// read this small generated index instead.
//
// Run after adding or renaming a spec: npx tsx scripts/anim-index.ts
// The /exercise-animations route refuses to build if this file is stale.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SPECS } from "../src/lib/exercise-anim/exercises";
import { animationSlug } from "../src/lib/exercise-anim/slug";

const entries: Record<string, { primary: string[]; secondary: string[] }> = {};
const aliases: Record<string, string> = {};
for (const spec of SPECS) {
  const slug = animationSlug(spec.name);
  if (entries[slug] || aliases[slug]) throw new Error(`Two specs share the slug ${slug}`);
  entries[slug] = { primary: [...spec.primary], secondary: [...(spec.secondary ?? [])] };
  for (const name of spec.aka ?? []) {
    const alias = animationSlug(name);
    if (alias === slug) continue;
    if (entries[alias] || aliases[alias]) throw new Error(`Alias ${name} collides with ${alias}`);
    aliases[alias] = slug;
  }
}

// One entry per line: readable in a diff, and a third the size of indented
// JSON.
const lines = <T,>(o: Record<string, T>) =>
  `{\n${Object.entries(o)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n")}\n}`;
const out = `// GENERATED by scripts/anim-index.ts — do not edit by hand.
//
// Every exercise that has an animation, keyed by animationSlug(name), with the
// muscles it lights up; and the alternative names that share a drawing.

export const ANIMATIONS: Record<string, { primary: string[]; secondary: string[] }> = ${lines(entries)};

export const ANIMATION_ALIASES: Record<string, string> = ${lines(aliases)};
`;
writeFileSync(join(__dirname, "../src/lib/exercise-anim/index.ts"), out);
console.log(`${Object.keys(entries).length} animations, ${Object.keys(aliases).length} aliases`);
